
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '294F563D543E242B042AEEBF645E1862'
    
_lr_action_items = {';':([27,28,29,32,33,34,36,37,38,42,],[-36,-36,-36,40,-35,41,-26,43,-33,-25,]),'OBJECT':([6,40,41,43,],[12,12,12,12,]),'STRUCT':([6,40,41,43,],[23,23,23,23,]),'VARS':([4,30,],[6,6,]),'INT':([6,40,41,43,],[16,16,16,16,]),'FLOAT':([6,40,41,43,],[17,17,17,17,]),',':([28,],[35,]),'PROGRAM':([0,],[2,]),'DICT':([6,40,41,43,],[19,19,19,19,]),'STRING':([6,40,41,43,],[18,18,18,18,]),'BOOL':([6,40,41,43,],[20,20,20,20,]),'{':([3,25,],[4,30,]),'MAIN':([4,5,7,8,9,10,11,13,14,15,22,24,40,41,43,46,47,48,49,50,],[-36,-36,-2,-3,-36,25,-5,-20,-19,-21,-6,-4,-36,-36,-36,-24,-27,-28,-22,-23,]),'}':([7,8,13,14,15,22,26,30,39,40,41,43,44,45,46,47,48,49,50,51,],[-2,-3,-20,-19,-21,-6,31,-36,-36,-36,-36,-36,51,-29,-24,-27,-28,-22,-23,-12,]),'ID':([2,12,16,17,18,19,20,21,23,35,],[3,-10,-7,-8,-9,27,-11,28,29,42,]),'$end':([1,31,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'a':([4,30,],[5,39,]),'function':([5,9,],[9,9,]),'b':([5,9,],[10,24,]),'e':([6,40,41,43,],[13,13,13,13,]),'d':([6,40,41,43,],[14,14,14,14,]),'vars':([4,30,],[7,7,]),'f':([6,40,41,43,],[15,15,15,15,]),'h':([40,41,43,],[46,49,50,]),'body':([39,],[44,]),'g':([28,],[34,]),'program':([0,],[1,]),'dict':([27,],[32,]),'main':([10,],[26,]),'type':([6,40,41,43,],[21,21,21,21,]),'declare':([6,40,41,43,],[22,47,47,47,]),'empty':([4,5,9,27,28,29,30,39,40,41,43,],[8,11,11,33,36,38,8,45,48,48,48,]),'struct':([29,],[37,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PROGRAM ID { a b main }','program',7,'p_program','CT.py',56),
  ('a -> vars','a',1,'p_a','CT.py',61),
  ('a -> empty','a',1,'p_a','CT.py',62),
  ('b -> function b','b',2,'p_b','CT.py',68),
  ('b -> empty','b',1,'p_b','CT.py',69),
  ('vars -> VARS declare','vars',2,'p_vars','CT.py',73),
  ('type -> INT','type',1,'p_type','CT.py',78),
  ('type -> FLOAT','type',1,'p_type','CT.py',79),
  ('type -> STRING','type',1,'p_type','CT.py',80),
  ('type -> OBJECT','type',1,'p_type','CT.py',81),
  ('type -> BOOL','type',1,'p_type','CT.py',82),
  ('main -> MAIN { a body }','main',5,'p_main','CT.py',87),
  ('instr -> c ;','instr',2,'p_instr','CT.py',92),
  ('instr -> condition','instr',1,'p_instr','CT.py',93),
  ('instr -> cycle','instr',1,'p_instr','CT.py',94),
  ('c -> assign','c',1,'p_c','CT.py',98),
  ('c -> funcCall','c',1,'p_c','CT.py',99),
  ('function -> empty','function',1,'p_function','CT.py',103),
  ('declare -> d','declare',1,'p_declare','CT.py',108),
  ('declare -> e','declare',1,'p_declare','CT.py',109),
  ('declare -> f','declare',1,'p_declare','CT.py',110),
  ('d -> type ID g ; h','d',5,'p_d','CT.py',115),
  ('e -> STRUCT ID struct ; h','e',5,'p_e','CT.py',120),
  ('f -> DICT ID dict ; h','f',5,'p_f','CT.py',125),
  ('g -> , ID','g',2,'p_g','CT.py',130),
  ('g -> empty','g',1,'p_g','CT.py',131),
  ('h -> declare','h',1,'p_h','CT.py',136),
  ('h -> empty','h',1,'p_h','CT.py',137),
  ('body -> empty','body',1,'p_body','CT.py',142),
  ('cycle -> empty','cycle',1,'p_cycle','CT.py',147),
  ('assign -> empty','assign',1,'p_assign','CT.py',152),
  ('funcCall -> empty','funcCall',1,'p_funcCall','CT.py',157),
  ('struct -> empty','struct',1,'p_struct','CT.py',162),
  ('condition -> empty','condition',1,'p_condition','CT.py',167),
  ('dict -> empty','dict',1,'p_dict','CT.py',172),
  ('empty -> <empty>','empty',0,'p_empty','CT.py',177),
]
