
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '07C79264BB3F9B0EAB4789BDD2B64F55'
    
_lr_action_items = {'VARS':([4,32,61,],[6,6,6,]),'OBJECT':([6,31,34,36,40,44,47,50,51,52,53,60,63,72,76,77,78,84,],[13,13,13,13,-41,13,13,13,13,-40,13,-55,13,-55,-28,13,-30,-29,]),'PROGRAM':([0,],[2,]),')':([13,17,18,19,21,40,44,52,57,58,59,60,72,74,76,78,84,],[-10,-7,-8,-9,-11,-41,-55,-40,-33,71,-34,-55,-55,80,-28,-30,-29,]),'(':([28,29,],[34,36,]),',':([30,60,],[39,39,]),'BOOL':([6,31,34,36,40,44,47,50,51,52,53,60,63,72,76,77,78,84,],[21,21,21,21,-41,21,21,21,21,-40,21,-55,21,-55,-28,21,-30,-29,]),';':([30,37,38,40,41,52,60,72,75,80,81,83,87,],[-55,50,51,-41,53,-40,-55,77,-55,-52,-48,-50,-49,]),':':([13,17,18,19,21,49,],[-10,-7,-8,-9,-11,63,]),'$end':([1,33,],[0,-1,]),'STRING':([6,31,34,36,40,44,47,50,51,52,53,60,63,72,76,77,78,84,],[19,19,19,19,-41,19,19,19,19,-40,19,-55,19,-55,-28,19,-30,-29,]),'RETURNS':([35,71,],[47,-32,]),'FUNC':([4,5,7,8,9,14,15,16,23,50,51,53,64,65,66,67,68,85,],[-55,11,-2,-3,11,-19,-18,-20,-6,-55,-55,-55,-39,-42,-43,-37,-38,-31,]),'[':([13,17,18,19,21,42,75,],[-10,-7,-8,-9,-11,54,82,]),']':([69,86,],[75,87,]),'ID':([2,11,13,17,18,19,20,21,22,24,39,45,],[3,28,-10,-7,-8,-9,29,-11,30,31,52,60,]),'STRUCT':([6,50,51,53,],[24,24,24,24,]),'INT':([6,31,34,36,40,44,47,50,51,52,53,60,63,72,76,77,78,84,],[17,17,17,17,-41,17,17,17,17,-40,17,-55,17,-55,-28,17,-30,-29,]),'FLOAT':([6,31,34,36,40,44,47,50,51,52,53,60,63,72,76,77,78,84,],[18,18,18,18,-41,18,18,18,18,-40,18,-55,18,-55,-28,18,-30,-29,]),'DICT':([6,50,51,53,],[20,20,20,20,]),'CTED':([54,82,],[69,86,]),'{':([3,13,17,18,19,21,26,35,46,48,62,71,],[4,-10,-7,-8,-9,-11,32,-55,61,-36,-35,-32,]),'MAIN':([4,5,7,8,9,10,12,14,15,16,23,25,50,51,53,64,65,66,67,68,85,],[-55,-55,-2,-3,-55,26,-5,-19,-18,-20,-6,-4,-55,-55,-55,-39,-42,-43,-37,-38,-31,]),'}':([7,8,14,15,16,23,27,32,43,50,51,53,55,56,61,64,65,66,67,68,70,73,79,],[-2,-3,-19,-18,-20,-6,33,-55,-55,-55,-55,-55,70,-44,-55,-39,-42,-43,-37,-38,-12,-55,85,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'body':([43,73,],[55,79,]),'vars':([4,32,61,],[7,7,7,]),'optionalMatrix':([75,],[81,]),'struct':([31,],[41,]),'param':([34,44,77,],[44,57,84,]),'program':([0,],[1,]),'dict':([29,],[37,]),'main':([10,],[27,]),'type':([6,31,34,36,44,47,50,51,53,63,77,],[22,42,45,49,45,62,22,22,22,74,45,]),'empty':([4,5,9,30,32,35,43,44,50,51,53,60,61,72,73,75,],[8,12,12,40,8,48,56,59,66,66,66,40,8,78,56,83,]),'function':([5,9,],[9,9,]),'a':([4,32,61,],[5,43,73,]),'b':([5,9,],[10,25,]),'e':([6,50,51,53,],[14,14,14,14,]),'d':([6,50,51,53,],[15,15,15,15,]),'g':([30,60,],[38,72,]),'f':([6,50,51,53,],[16,16,16,16,]),'h':([50,51,53,],[64,67,68,]),'k':([72,],[76,]),'m':([35,],[46,]),'l':([28,],[35,]),'n':([44,],[58,]),'declare':([6,50,51,53,],[23,65,65,65,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PROGRAM ID { a b main }','program',7,'p_program','CT.py',56),
  ('a -> vars','a',1,'p_a','CT.py',61),
  ('a -> empty','a',1,'p_a','CT.py',62),
  ('b -> function b','b',2,'p_b','CT.py',67),
  ('b -> empty','b',1,'p_b','CT.py',68),
  ('vars -> VARS declare','vars',2,'p_vars','CT.py',72),
  ('type -> INT','type',1,'p_type','CT.py',77),
  ('type -> FLOAT','type',1,'p_type','CT.py',78),
  ('type -> STRING','type',1,'p_type','CT.py',79),
  ('type -> OBJECT','type',1,'p_type','CT.py',80),
  ('type -> BOOL','type',1,'p_type','CT.py',81),
  ('main -> MAIN { a body }','main',5,'p_main','CT.py',86),
  ('instr -> c ;','instr',2,'p_instr','CT.py',91),
  ('instr -> condition','instr',1,'p_instr','CT.py',92),
  ('instr -> cycle','instr',1,'p_instr','CT.py',93),
  ('c -> assign','c',1,'p_c','CT.py',97),
  ('c -> funcCall','c',1,'p_c','CT.py',98),
  ('declare -> d','declare',1,'p_declare','CT.py',102),
  ('declare -> e','declare',1,'p_declare','CT.py',103),
  ('declare -> f','declare',1,'p_declare','CT.py',104),
  ('init -> = i','init',2,'p_init','CT.py',109),
  ('i -> expresion','i',1,'p_i','CT.py',114),
  ('i -> funcCall','i',1,'p_i','CT.py',115),
  ('initDict -> = ( j : j )','initDict',6,'p_initDict','CT.py',120),
  ('j -> CTES','j',1,'p_j','CT.py',125),
  ('j -> cte','j',1,'p_j','CT.py',126),
  ('j -> ID','j',1,'p_j','CT.py',127),
  ('param -> type ID g k','param',4,'p_param','CT.py',132),
  ('k -> ; param','k',2,'p_k','CT.py',137),
  ('k -> empty','k',1,'p_k','CT.py',138),
  ('function -> FUNC ID l m { a body }','function',8,'p_function','CT.py',143),
  ('l -> ( param n )','l',4,'p_l','CT.py',148),
  ('n -> param','n',1,'p_n','CT.py',153),
  ('n -> empty','n',1,'p_n','CT.py',154),
  ('m -> RETURNS type','m',2,'p_m','CT.py',159),
  ('m -> empty','m',1,'p_m','CT.py',160),
  ('d -> type ID g ; h','d',5,'p_d','CT.py',165),
  ('e -> STRUCT ID struct ; h','e',5,'p_e','CT.py',170),
  ('f -> DICT ID dict ; h','f',5,'p_f','CT.py',175),
  ('g -> , ID','g',2,'p_g','CT.py',180),
  ('g -> empty','g',1,'p_g','CT.py',181),
  ('h -> declare','h',1,'p_h','CT.py',186),
  ('h -> empty','h',1,'p_h','CT.py',187),
  ('body -> empty','body',1,'p_body','CT.py',192),
  ('cycle -> empty','cycle',1,'p_cycle','CT.py',197),
  ('assign -> empty','assign',1,'p_assign','CT.py',202),
  ('funcCall -> empty','funcCall',1,'p_funcCall','CT.py',207),
  ('struct -> type [ CTED ] optionalMatrix','struct',5,'p_struct','CT.py',212),
  ('optionalMatrix -> [ CTED ]','optionalMatrix',3,'p_optionalMatrix','CT.py',217),
  ('optionalMatrix -> empty','optionalMatrix',1,'p_optionalMatrix','CT.py',218),
  ('condition -> empty','condition',1,'p_condition','CT.py',223),
  ('dict -> ( type : type )','dict',5,'p_dict','CT.py',228),
  ('expresion -> empty','expresion',1,'p_expresion','CT.py',233),
  ('cte -> empty','cte',1,'p_cte','CT.py',238),
  ('empty -> <empty>','empty',0,'p_empty','CT.py',243),
]
